apiVersion: v2
name: brokerapp
description: BrokerApp umbrella chart — bundles db, api, web, worker, backup
type: application
version: 0.2.0
appVersion: "0.2.0"

dependencies:
  - name: brokerapp-db
    alias: db
    version: 0.1.0
    repository: "file://../db"
  - name: brokerapp-api
    alias: api
    version: 0.1.0
    repository: "file://../api"
  - name: brokerapp-web
    alias: web
    version: 0.1.0
    repository: "file://../web"
  - name: brokerapp-worker
    alias: worker
    version: 0.1.0
    repository: "file://../worker"
  - name: brokerapp-backup
    alias: backup
    version: 0.1.0
    repository: "file://../backup"
