"""Alembic environment.

Phase-0 decision (ADR-0008 placeholder, refined in commit log): we use
`autogenerate` for ordinary tables and apply a **post-processing hook**
that injects TimescaleDB-specific statements (hypertable creation,
continuous aggregates, retention policies) where models opt in via the
table's `info` dict.

A model can mark its table as a hypertable like so:

    class Bar(Base):
        __tablename__ = "bars"
        __table_args__ = (..., {
            "info": {
                "timescale": {
                    "hypertable": {
                        "time_column_name": "time",
                        "chunk_time_interval": "INTERVAL '7 days'",
                    },
                },
            },
        })

The hook scans `target_metadata.tables` after every autogenerate run and
emits the corresponding `SELECT create_hypertable(...)` etc. into the
revision script.
"""

from __future__ import annotations

import os
from logging.config import fileConfig
from typing import Any

from alembic import context
from alembic.operations import ops
from brokerapp_db.base import metadata as target_metadata
from sqlalchemy import engine_from_config, pool

# ---------------------------------------------------------------------------
# Alembic config
# ---------------------------------------------------------------------------

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Resolve the DB URL from env at runtime.
DB_URL = os.environ.get("DATABASE_URL") or config.get_main_option("sqlalchemy.url")
config.set_main_option("sqlalchemy.url", DB_URL or "")


# ---------------------------------------------------------------------------
# Schemas Alembic should manage
# ---------------------------------------------------------------------------

INCLUDED_SCHEMAS = {"app", "market"}


def include_object(obj: Any, name: str, type_: str, reflected: bool, compare_to: Any) -> bool:
    """Limit autogenerate to our schemas; never touch extension- or system-owned
    objects (timescaledb_information.*, _timescaledb_*, pg_*, etc.)."""
    if type_ == "schema":
        return name in INCLUDED_SCHEMAS
    if hasattr(obj, "schema") and obj.schema is not None:
        return obj.schema in INCLUDED_SCHEMAS
    # Default: include top-level objects without an explicit schema (Alembic
    # places them in 'app' via the Base metadata default).
    return True


# ---------------------------------------------------------------------------
# Post-processing hook for TimescaleDB-aware tables
# ---------------------------------------------------------------------------


def process_revision_directives(
    context_: Any,
    revision: tuple[str, ...],
    directives: list[Any],
) -> None:
    """Append TimescaleDB statements to autogenerated revisions.

    Runs after Alembic produces the ordinary CREATE TABLE / DROP TABLE
    operations; we then walk the metadata, find tables that opted into
    Timescale features via `info["timescale"]`, and inject the appropriate
    `op.execute(...)` calls in the right place.
    """
    if not directives:
        return

    script = directives[0]
    if script.upgrade_ops is None:
        return

    # Locate every hypertable declared in the metadata.
    for table in target_metadata.sorted_tables:
        ts_info = table.info.get("timescale") if table.info else None
        if not ts_info:
            continue

        hypertable_cfg: dict[str, Any] | None = ts_info.get("hypertable")
        if hypertable_cfg is None:
            continue

        time_col = hypertable_cfg.get("time_column_name", "time")
        chunk = hypertable_cfg.get("chunk_time_interval", "INTERVAL '7 days'")
        qualified = f'"{table.schema}"."{table.name}"' if table.schema else f'"{table.name}"'

        sql = (
            f"SELECT create_hypertable("
            f"'{qualified}', '{time_col}', "
            f"chunk_time_interval => {chunk}, "
            f"if_not_exists => TRUE);"
        )

        script.upgrade_ops.ops.append(
            _make_execute_op(sql),
        )

        # Down-migration: convert hypertable back to a plain table (TimescaleDB
        # has no first-class drop — dropping the table works because the
        # hypertable metadata follows. We emit a no-op marker so reviewers
        # see the intent.)
        if script.downgrade_ops is not None:
            script.downgrade_ops.ops.insert(
                0,
                _make_execute_op(
                    f"-- hypertable {qualified} torn down with its table",
                ),
            )


def _make_execute_op(sql: str) -> Any:
    """Build an `op.execute(sql)` ExecuteSQLOp."""
    return ops.ExecuteSQLOp(sql)


# ---------------------------------------------------------------------------
# Runners
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Generate SQL without a live connection."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        include_schemas=True,
        include_object=include_object,
        process_revision_directives=process_revision_directives,
        compare_type=True,
        compare_server_default=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_schemas=True,
            include_object=include_object,
            process_revision_directives=process_revision_directives,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
