apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db.fullname" . }}-migrate
  labels: {{- include "db.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "db.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          command: {{- toYaml .Values.migration.command | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ include "db.fullname" . }}:5432/$(POSTGRES_DB)"
