apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db.fullname" . }}
  labels: {{- include "db.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "db.fullname" . }}
  replicas: 1
  selector:
    matchLabels: {{- include "db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "db.selectorLabels" . | nindent 8 }}
    spec:
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: timescaledb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  labels: {{- include "db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector: {{- include "db.selectorLabels" . | nindent 4 }}
