/**
 * Generated by `openapi-typescript` from apps/api/openapi.json.
 *
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter @brokerapp/api-client generate`.
 *
 * This file is checked into git so the front-end builds without a live API.
 * CI re-runs the generator and fails on drift.
 */

export type AssetClass = "stock" | "etf" | "index" | "crypto" | "fx" | "commodity";
export type BarGranularity = "5m" | "15m" | "1h" | "1d";

export interface AssetOut {
  id: string;
  symbol: string;
  name: string | null;
  asset_class: AssetClass;
  exchange: string | null;
  currency: string | null;
  source: string;
  calendar: string;
  enabled: boolean;
}

export interface BarOut {
  time: string;
  granularity: BarGranularity;
  open: string;
  high: string;
  low: string;
  close: string;
  volume: string | null;
  adj_close: string | null;
  source: string;
}

export interface BarsResponse {
  asset_id: string;
  granularity: BarGranularity;
  bars: BarOut[];
}

export interface WatchlistOut {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
}

export interface WatchlistAssetOut {
  asset_id: string;
  added_at: string;
}

export interface WatchlistDetail extends WatchlistOut {
  members: WatchlistAssetOut[];
}

export interface WatchlistCreate {
  name: string;
  description?: string | null;
}

export interface WatchlistUpdate {
  name?: string | null;
  description?: string | null;
}

export interface WatchlistMemberAdd {
  asset_id: string;
}

export interface AssetCreate {
  symbol: string;
  name?: string | null;
  asset_class: AssetClass;
  exchange?: string | null;
  currency?: string | null;
  source?: string;
  source_symbol?: string | null;
  calendar?: string;
}

export interface PageOfAssetOut {
  items: AssetOut[];
  next_cursor: string | null;
}

export interface FieldError {
  field: string;
  message: string;
}

export interface ProblemDetail {
  type: string;
  title: string;
  status: number;
  detail?: string | null;
  instance?: string | null;
  code: string;
  request_id?: string | null;
  errors?: FieldError[] | null;
}

export type ForecastHorizon = "1h" | "1d" | "5d" | "20d";

export interface ForecastOut {
  id: string;
  asset_id: string;
  model_id: string;
  as_of: string;
  horizon: ForecastHorizon;
  target_time: string;
  value: string;
  quantiles: Record<string, number> | null;
}

export interface BacktestOut {
  id: string;
  asset_id: string;
  model_id: string;
  horizon: ForecastHorizon;
  train_start: string;
  train_end: string;
  test_start: string;
  test_end: string;
  metrics: Record<string, number>;
}

export interface ForecastRunResponse {
  asset_id: string;
  dispatched: boolean;
  model: string;
}
